### ISSUE TITLE
[Public page] Header menu is not responsive

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/harta-help2help-ucraina#16]
All the items in the header menu should be responsive for all the screen sizes. Please see the issue in the printscreen attached
<img width="1398" alt="Screenshot 2023-08-03 at 14 46 37" src="https://github.com/code4romania/harta-help2help-ucraina/assets/111346300/4b0d6d62-e0e3-4f1d-b59a-1ecad1117de8">

**Comment by andreiio** [comment]
FYI I've dropped the redundant "Help to help Ukraine" link in the menu to help with responsiveness
