### ISSUE TITLE
[Public Page] Texts for Hero Sections

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/harta-help2help-ucraina#23]
Pagina ONG-uri
![Screenshot 2023-08-10 at 11 42 03](https://github.com/code4romania/harta-help2help-ucraina/assets/111346300/13d330ea-3e6e-499d-b087-97b148a9126b)

Title - ONG-uri (organizații)
Text - Caută o organizație care te poate ajuta cu un serviciu pentru nevoile tale

**Comment by vilenbejenaru** [comment]
Also updated EN/UK - please verify translations
